export default {
  restaurants: [
    {
      _id: '64f8b4a2e4b0d12a3f8b4567',
      name: 'Restaurante Sabor Caseiro',
      stars: 4,
      address: {
        zipCode: '12345-678',
        street: 'Rua das Flores',
        number: '123',
        district: 'Centro',
        city: 'Cidade Exemplo',
        state: 'EX',
      },
      logoImage: 'https://example.com/logo1.png',
      products: [
        {
          _id: '64f8c1a2e4b0d12a3f8b1001',
          name: 'Feijoada Completa',
          price: 25.90,
          category: 'Prato Principal',
          stock: 50,
          description: 'Feijoada completa com acompanhamentos.',
          image: 'https://example.com/feijoada.jpg',
        },
        {
          _id: '64f8c1a2e4b0d12a3f8b1002',
          name: 'Strogonoff de Frango',
          price: 22.50,
          category: 'Prato Principal',
          stock: 40,
          description: 'Strogonoff de frango com arroz e batata palha.',
          image: 'https://example.com/strogonoff.jpg',
        },
        {
          _id: '64f8c1a2e4b0d12a3f8b1003',
          name: 'Lasanha à Bolonhesa',
          price: 28.00,
          category: 'Prato Principal',
          stock: 30,
          description: 'Lasanha recheada com molho bolonhesa.',
          image: 'https://example.com/lasanha.jpg',
        },
        {
          _id: '64f8c1a2e4b0d12a3f8b1004',
          name: 'Suco de Laranja Natural',
          price: 8.00,
          category: 'Bebida',
          stock: 100,
          description: 'Suco de laranja natural.',
          image: 'https://example.com/suco.jpg',
        },
        {
          _id: '64f8c1a2e4b0d12a3f8b1005',
          name: 'Salada Caesar',
          price: 15.00,
          category: 'Entrada',
          stock: 20,
          description: 'Salada Caesar com frango grelhado.',
          image: 'https://example.com/salada.jpg',
        },
      ],
    },
    {
      _id: '64f8b4a2e4b0d12a3f8b4568',
      name: 'Pizzaria Forno a Lenha',
      stars: 5,
      address: {
        zipCode: '98765-432',
        street: 'Avenida dos Sabores',
        number: '456',
        district: 'Bairro Novo',
        city: 'Cidade Exemplo',
        state: 'EX',
      },
      logoImage: 'https://example.com/logo2.png',
      products: [
        {
          _id: '64f8c1a2e4b0d12a3f8b2001',
          name: 'Pizza Margherita',
          price: 35.00,
          category: 'Pizza',
          stock: 25,
          description: 'Pizza com molho de tomate, mussarela e manjericão.',
          image: 'https://example.com/margherita.jpg',
        },
        {
          _id: '64f8c1a2e4b0d12a3f8b2002',
          name: 'Pizza Calabresa',
          price: 38.00,
          category: 'Pizza',
          stock: 30,
          description: 'Pizza com calabresa fatiada e cebola.',
          image: 'https://example.com/calabresa.jpg',
        },
        {
          _id: '64f8c1a2e4b0d12a3f8b2003',
          name: 'Pizza Quatro Queijos',
          price: 40.00,
          category: 'Pizza',
          stock: 20,
          description: 'Pizza com mussarela, provolone, parmesão e gorgonzola.',
          image: 'https://example.com/quatroqueijos.jpg',
        },
        {
          _id: '64f8c1a2e4b0d12a3f8b2004',
          name: 'Refrigerante Lata',
          price: 6.00,
          category: 'Bebida',
          stock: 80,
          description: 'Refrigerante em lata de 350ml.',
          image: 'https://example.com/refri.jpg',
        },
        {
          _id: '64f8c1a2e4b0d12a3f8b2005',
          name: 'Sorvete de Chocolate',
          price: 12.00,
          category: 'Sobremesa',
          stock: 15,
          description: 'Sorvete de chocolate cremoso.',
          image: 'https://example.com/sorvete.jpg',
        },
      ],
    },
  ],
};
